spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=#Bhulgaya123

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/quantitydb
db.username=root
db.password=#Bhulgaya123
db.pool.size=5

app.repository.type=database